/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef TFTOBBENUMBER_H
#define TFTOBBENUMBER_H

/* function declarations */
void init_tfTobbeNumber(void);
Netsnmp_Node_Handler handle_tfTobbeNumber;

#endif /* TFTOBBENUMBER_H */
