/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "tfTobbeNumber.h"

#include <stdint.h>

/* example: 0x0000444400004444LL; */


/* https://groups.google.com/g/mailing.unix.net-snmp-users/c/rXN37ttUpiY?pli=1 */

/* From: #include <net-snmp/library/asn1.h> 
struct counter64 {
  u_long high;
  u_long low;
};
*/
/* should work  18410715276690587647 */
/* uint64_t c64 = 18410715276690587648; */
/* const uint64_t c64val = 0xFF80000000000000LL; */
/* const uint64_t c64val = 0x00000000000000FFLL; */
const uint64_t c64val = 0xFFFFFFFFFFFFFFFFLL;
/* const uint64_t c64val = 0x8FFFFFFFFFFFFFFFLL; */
/* const uint64_t c64val = 0xF000000000000000LL; */
/* 281470681808895 = FFFF0000FFFF */
/*const uint64_t c64val = 0xFF80000000000000LL;*/

struct counter64 counter = {(u_long) ((c64val >> 32) & 0xffffffff) , (u_long) ((c64val) & 0xffffffff) };

/*counter.high = (u_long) ((c64val >> 32) & 0xffff);
counter.low = (u_long) ((c64val) & 0xffff);
*/
/* counter.high = ((c64val >> 32) & 0xffff); */
/* counter.low = ((c64val) & 0xffff); */

/* uint64_t c64 = 18446744073709551615; */

/** Initializes the tfTobbeNumber module */
void
init_tfTobbeNumber(void)
{
    const oid tfTobbeNumber_oid[] = { 1,3,6,1,4,1,24961,2,103,1,1,1 };

  DEBUGMSGTL(("tfTobbeNumber", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("tfTobbeNumber", handle_tfTobbeNumber,
                               tfTobbeNumber_oid, OID_LENGTH(tfTobbeNumber_oid),
                               HANDLER_CAN_RONLY
        ));
}

int
handle_tfTobbeNumber(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */

    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_COUNTER64,
                                     /* XXX: a pointer to the scalar's data */
                                     (u_char *) &counter,
                                     /* XXX: the length of the data in bytes */
                                     sizeof(counter));
            break;


        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_tfTobbeNumber\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
